name = "Nicemappack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "035c6364a0b4199c368884767c047bd8b69af9d82a92afccfc915591b0ed5b96"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
