name = "Nicemappack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a8316bb8e213160354d03e81d17b8aad17e9bf348340cf5dddccb9adf39ef09"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
